cnf(add_assoc,axiom,plus(A, plus(B, C)) = plus(plus(A, B), C)).
cnf(add_comm,axiom,plus(A, B) = plus(B, A)).
cnf(add_const,axiom,plus(mul(X, A), mul(Y, B)) = if(and(ne(B, num0), eq(mod(A, B), num0)), mul(plus(mul(X, div(A, B)), Y), B), plus(mul(X, A), mul(Y, B)))).
cnf(add_denom_div,axiom,div(plus(A, mul(B, C)), B) = if(is_not_zero(B), plus(div(A, B), C), div(plus(A, mul(B, C)), B))).
cnf(add_denom_mul,axiom,plus(div(A, B), C) = if(is_not_zero(B), div(plus(A, mul(B, C)), B), plus(div(A, B), C))).
cnf(add_dist_mul,axiom,mul(A, plus(B, C)) = plus(mul(A, B), mul(A, C))).
cnf(add_div_mod,axiom,plus(div(X, num2), mod(X, num2)) = div(plus(X, num1), num2)).
cnf(add_fact_mul,axiom,plus(mul(A, B), mul(A, C)) = mul(A, plus(B, C))).
cnf(add_zero,axiom,plus(A, num0) = A).
cnf(and_assoc,axiom,and(A, and(B, C)) = and(and(A, B), C)).
cnf(and_comm,axiom,and(Y, X) = and(X, Y)).
cnf(and_eq_eq,axiom,and(eq(X, C0), eq(X, C1)) = if(ne(C1, C0), num0, and(eq(X, C0), eq(X, C1)))).
cnf(and_eqlt_eqgt_to_0,axiom,and(le(C0, X), le(X, C1)) = if(lt(C1, C0), num0, and(le(C0, X), le(X, C1)))).
cnf(and_eqlt_gt_to_0,axiom,and(le(C0, X), lt(X, C1)) = if(le(C1, C0), num0, and(le(C0, X), lt(X, C1)))).
cnf(and_eqlt_to_max,axiom,and(le(Y, X), le(Z, X)) = le(max(Y, Z), X)).
cnf(and_eqlt_to_min,axiom,and(le(X, Y), le(X, Z)) = le(X, min(Y, Z))).
cnf(and_ineq_eq,axiom,and(ne(X, C0), eq(X, C1)) = if(ne(C1, C0), eq(X, C1), and(ne(X, C0), eq(X, C1)))).
cnf(and_lt_gt_to_0,axiom,and(lt(C0, X), lt(X, C1)) = if(le(C1, plus(C0, num1)), num0, and(lt(C0, X), lt(X, C1)))).
cnf(and_lt_to_max,axiom,and(lt(Y, X), lt(Z, X)) = lt(max(Y, Z), X)).
cnf(and_lt_to_min,axiom,and(lt(X, Y), lt(X, Z)) = lt(X, min(Y, Z))).
cnf(and_max_to_eqlt,axiom,ge(X, max(Y, Z)) = and(le(Z, X), le(Y, X))).
cnf(and_max_to_lt,axiom,gt(X, max(Y, Z)) = and(lt(Z, X), lt(Y, X))).
cnf(and_min_to_eqlt,axiom,le(X, min(Y, Z)) = and(le(X, Y), le(X, Z))).
cnf(and_min_to_lt,axiom,lt(X, min(Y, Z)) = and(lt(X, Y), lt(X, Z))).
cnf(and_over_or,axiom,and(A, or(B, C)) = or(and(A, B), and(A, C))).
cnf(and_x_1,axiom,and(num1, X) = X).
cnf(and_x_not_x,axiom,and(X, not(X)) = num0).
cnf(and_x_x,axiom,and(X, X) = X).
cnf(div_cancel,axiom,div(A, A) = if(is_not_zero(A), num1, div(A, A))).
cnf(div_cancel_mul,axiom,div(mul(Y, X), X) = if(is_not_zero(X), Y, div(mul(Y, X), X))).
cnf(div_consts_add,axiom,div(plus(mul(X, A), Y), B) = if(and(gt(B, num0), eq(mod(A, B), num0)), plus(mul(X, div(A, B)), div(Y, B)), div(plus(mul(X, A), Y), B))).
cnf(div_consts_div,axiom,div(mul(X, A), B) = if(and(gt(A, num0), eq(mod(B, A), num0)), div(X, div(B, A)), div(mul(X, A), B))).
cnf(div_consts_mul,axiom,div(mul(X, A), B) = if(and(gt(B, num0), eq(mod(A, B), num0)), mul(X, div(A, B)), div(mul(X, A), B))).
cnf(div_minus_down,axiom,div(mul(numneg1, A), B) = div(A, mul(numneg1, B))).
cnf(div_minus_in,axiom,mul(numneg1, div(A, B)) = div(mul(numneg1, A), B)).
cnf(div_minus_out,axiom,div(mul(numneg1, A), B) = mul(numneg1, div(A, B))).
cnf(div_minus_up,axiom,div(A, mul(numneg1, B)) = div(mul(numneg1, A), B)).
cnf(div_separate,axiom,div(plus(X, A), B) = if(and(gt(B, num0), eq(mod(A, B), num0)), plus(div(X, B), div(A, B)), div(plus(X, A), B))).
cnf(div_zero,axiom,div(num0, X) = num0).
cnf(eq_a_b,axiom,eq(mul(A, X), B) = if(and(ne(A, num0), ne(mod(B, A), num0)), num0, eq(mul(A, X), B))).
cnf(eq_comm,axiom,eq(X, Y) = eq(Y, X)).
cnf(eq_lt_min,axiom,le(Y, X) = eq(min(X, Y), Y)).
cnf(eq_max_c_neg,axiom,eq(max(X, C), num0) = if(is_const_neg(C), eq(X, num0), eq(max(X, C), num0))).
cnf(eq_max_c_pos,axiom,eq(max(X, C), num0) = if(is_const_pos(C), num0, eq(max(X, C), num0))).
cnf(eq_max_lt,axiom,eq(max(X, Y), Y) = le(X, Y)).
cnf(eq_min_c_neg,axiom,eq(min(X, C), num0) = if(is_const_pos(C), eq(X, num0), eq(min(X, C), num0))).
cnf(eq_min_c_pos,axiom,eq(min(X, C), num0) = if(is_const_neg(C), num0, eq(min(X, C), num0))).
cnf(eq_min_lt,axiom,eq(min(X, Y), Y) = le(Y, X)).
cnf(eq_mul_x_y_0,axiom,eq(mul(X, Y), num0) = or(eq(X, num0), eq(Y, num0))).
cnf(eq_swap,axiom,eq(plus(X, Y), Z) = eq(X, minus(Z, Y))).
cnf(eq_x_x,axiom,eq(X, X) = num1).
cnf(eq_x_y_0,axiom,eq(X, Y) = eq(minus(X, Y), num0)).
cnf(eqgt_to_not_lt,axiom,ge(X, Y) = not(lt(X, Y))).
cnf(eqlt_to_not_gt,axiom,le(X, Y) = not(lt(Y, X))).
cnf(gt_to_lt,axiom,gt(X, Z) = lt(Z, X)).
cnf(ineq_to_eq,axiom,ne(X, Y) = not(eq(X, Y))).
cnf(lt_const_mod,axiom,lt(A, mod(X, B)) = if(le(A, neg(abs(B))), num1, lt(A, mod(X, B)))).
cnf(lt_const_mod_false,axiom,lt(A, mod(X, B)) = if(ge(A, abs(B)), num0, lt(A, mod(X, B)))).
cnf(lt_const_neg,axiom,lt(Y, num0) = if(is_const_neg(Y), num1, lt(Y, num0))).
cnf(lt_const_pos,axiom,lt(num0, Y) = if(is_const_pos(Y), num1, lt(num0, Y))).
cnf(lt_max_mutual_term,axiom,lt(max(Z, Y), max(X, Y)) = lt(max(Z, Y), X)).
cnf(lt_max_term_neg_term,axiom,lt(max(Z, Y), max(X, plus(Y, C0))) = if(is_const_neg(C0), lt(max(Z, Y), X), lt(max(Z, Y), max(X, plus(Y, C0))))).
cnf(lt_max_term_term_pos,axiom,lt(max(Z, plus(Y, C0)), max(X, Y)) = if(is_const_pos(C0), lt(max(Z, plus(Y, C0)), X), lt(max(Z, plus(Y, C0)), max(X, Y)))).
cnf(lt_min_max_cancel,axiom,lt(max(A, C), min(A, B)) = num0).
cnf(lt_min_mutual_term,axiom,lt(min(Z, Y), min(X, Y)) = lt(Z, min(X, Y))).
cnf(lt_min_term_cpos,axiom,lt(min(X, Y), plus(X, C0)) = if(is_const_pos(C0), num1, lt(min(X, Y), plus(X, C0)))).
cnf(lt_min_term_neg_term,axiom,lt(min(Z, plus(Y, C0)), min(X, Y)) = if(is_const_neg(C0), lt(min(Z, plus(Y, C0)), X), lt(min(Z, plus(Y, C0)), min(X, Y)))).
cnf(lt_min_term_term_pos,axiom,lt(min(Z, Y), min(X, plus(Y, C0))) = if(is_const_pos(C0), lt(min(Z, Y), X), lt(min(Z, Y), min(X, plus(Y, C0))))).
cnf(lt_mul_div_cancel,axiom,lt(Y, div(X, Z)) = if(is_const_pos(Z), lt(minus(mul(plus(Y, num1), Z), num1), X), lt(Y, div(X, Z)))).
cnf(lt_mul_pos_cancel,axiom,lt(mul(X, Y), Z) = if(is_const_pos(Y), lt(X, div(minus(plus(Z, Y), num1), Y)), lt(mul(X, Y), Z))).
cnf(lt_swap,axiom,lt(X, Y) = lt(mul(numneg1, Y), mul(numneg1, X))).
cnf(lt_swap_in,axiom,lt(plus(X, Y), Z) = lt(X, minus(Z, Y))).
cnf(lt_swap_out,axiom,lt(Z, plus(X, Y)) = lt(minus(Z, Y), X)).
cnf(lt_to_zero,axiom,lt(A, A) = num0).
cnf(lt_x_x_sub_a,axiom,lt(minus(A, Y), A) = if(is_const_pos(Y), num1, lt(minus(A, Y), A))).
cnf(max_consts_and,axiom,lt(max(Y, C0), C1) = and(lt(Y, C1), lt(C0, C1))).
cnf(max_consts_or,axiom,lt(C1, max(Y, C0)) = or(lt(C1, Y), lt(C1, C0))).
cnf(max_min_switch,axiom,max(min(X, C1), C0) = if(le(C0, C1), min(max(X, C0), C1), max(min(X, C1), C0))).
cnf(max_to_min,axiom,max(A, B) = mul(numneg1, min(mul(numneg1, A), mul(numneg1, B)))).
cnf(min_add_both,axiom,plus(min(X, Y), Z) = min(plus(X, Z), plus(Y, Z))).
cnf(min_ass,axiom,min(min(X, Y), Z) = min(X, min(Y, Z))).
cnf(min_comm,axiom,min(A, B) = min(B, A)).
cnf(min_consts_div_neg,axiom,min(mul(X, A), B) = if(and(lt(A, num0), eq(mod(B, A), num0)), mul(max(X, div(B, A)), A), min(mul(X, A), B))).
cnf(min_consts_div_pos,axiom,min(mul(X, A), B) = if(and(gt(A, num0), eq(mod(B, A), num0)), mul(min(X, div(B, A)), A), min(mul(X, A), B))).
cnf(min_consts_or,axiom,lt(min(Y, C0), C1) = or(lt(Y, C1), lt(C0, C1))).
cnf(min_div_in_neg,axiom,div(max(X, Y), Z) = if(is_const_neg(Z), min(div(X, Z), div(Y, Z)), div(max(X, Y), Z))).
cnf(min_div_in_pos,axiom,div(min(X, Y), Z) = if(is_const_pos(Z), min(div(X, Z), div(Y, Z)), div(min(X, Y), Z))).
cnf(min_div_mul,axiom,min(mul(div(X, C0), C0), X) = if(is_const_pos(C0), mul(div(X, C0), C0), min(mul(div(X, C0), C0), X))).
cnf(min_div_out_neg,axiom,min(div(X, Z), div(Y, Z)) = if(is_const_neg(Z), div(max(X, Y), Z), min(div(X, Z), div(Y, Z)))).
cnf(min_div_out_pos,axiom,min(div(X, Z), div(Y, Z)) = if(is_const_pos(Z), div(min(X, Y), Z), min(div(X, Z), div(Y, Z)))).
cnf(min_lt_cancel,axiom,lt(min(X, Y), X) = lt(Y, X)).
cnf(min_max,axiom,min(max(X, Y), X) = X).
cnf(min_max_const,axiom,min(max(X, C0), C1) = if(le(C1, C0), C1, min(max(X, C0), C1))).
cnf(min_max_max_x,axiom,min(max(X, Y), max(X, Z)) = max(min(Y, Z), X)).
cnf(min_max_min_y,axiom,min(max(min(X, Y), Z), Y) = min(max(X, Z), Y)).
cnf(min_max_switch,axiom,min(max(X, C0), C1) = if(le(C0, C1), max(min(X, C1), C0), min(max(X, C0), C1))).
cnf(min_min_div_neg,axiom,min(mul(X, A), mul(Y, B)) = if(and(lt(A, num0), eq(mod(B, A), num0)), mul(max(X, mul(Y, div(B, A))), A), min(mul(X, A), mul(Y, B)))).
cnf(min_min_div_pos,axiom,min(mul(X, A), mul(Y, B)) = if(and(gt(A, num0), eq(mod(B, A), num0)), mul(min(X, mul(Y, div(B, A))), A), min(mul(X, A), mul(Y, B)))).
cnf(min_mod_const_to_const,axiom,min(mod(X, C0), C1) = if(le(C1, minus(num1, abs(C0))), C1, min(mod(X, C0), C1))).
cnf(min_mod_const_to_mod,axiom,min(mod(X, C0), C1) = if(ge(C1, minus(abs(C0), num1)), mod(X, C0), min(mod(X, C0), C1))).
cnf(min_mul_in_neg,axiom,mul(min(X, Y), Z) = if(is_const_neg(Z), max(mul(X, Z), mul(Y, Z)), mul(min(X, Y), Z))).
cnf(min_mul_in_pos,axiom,mul(min(X, Y), Z) = if(is_const_pos(Z), min(mul(X, Z), mul(Y, Z)), mul(min(X, Y), Z))).
cnf(min_mul_out_neg,axiom,max(mul(X, Z), mul(Y, Z)) = if(is_const_neg(Z), mul(min(X, Y), Z), max(mul(X, Z), mul(Y, Z)))).
cnf(min_mul_out_pos,axiom,min(mul(X, Z), mul(Y, Z)) = if(is_const_pos(Z), mul(min(X, Y), Z), min(mul(X, Z), mul(Y, Z)))).
cnf(min_sub_both,axiom,min(plus(A, B), C) = plus(min(B, minus(C, A)), A)).
cnf(min_x_x,axiom,min(X, X) = X).
cnf(min_x_x_plus_a_neg,axiom,min(X, plus(X, A)) = if(is_const_neg(A), plus(X, A), min(X, plus(X, A)))).
cnf(min_x_x_plus_a_pos,axiom,min(X, plus(X, A)) = if(is_const_pos(A), X, min(X, plus(X, A)))).
cnf(mod_const_add,axiom,mod(X, C1) = if(le(C1, abs(X)), mod(plus(X, C1), C1), mod(X, C1))).
cnf(mod_const_sub,axiom,mod(X, C1) = if(le(C1, abs(X)), mod(minus(X, C1), C1), mod(X, C1))).
cnf(mod_consts,axiom,mod(plus(mul(X, C0), Y), C1) = if(and(ne(C1, num0), eq(mod(C0, C1), num0)), mod(Y, C1), mod(plus(mul(X, C0), Y), C1))).
cnf(mod_minus_in,axiom,mul(numneg1, mod(X, C)) = mod(mul(X, numneg1), C)).
cnf(mod_minus_out,axiom,mod(mul(X, numneg1), C) = mul(numneg1, mod(X, C))).
cnf(mod_multiple,axiom,mod(mul(C0, X), C1) = if(and(ne(C1, num0), eq(mod(C0, C1), num0)), num0, mod(mul(C0, X), C1))).
cnf(mod_one,axiom,mod(X, num1) = num0).
cnf(mod_two,axiom,mod(minus(X, Y), num2) = mod(plus(X, Y), num2)).
cnf(mod_x_x,axiom,mod(X, X) = num0).
cnf(mod_zero,axiom,mod(num0, X) = num0).
cnf(mul_assoc,axiom,mul(A, mul(B, C)) = mul(mul(A, B), C)).
cnf(mul_cancel_div,axiom,mul(div(A, B), B) = if(is_not_zero(B), minus(A, mod(A, B)), mul(div(A, B), B))).
cnf(mul_comm,axiom,mul(A, B) = mul(B, A)).
cnf(mul_max_min,axiom,mul(max(A, B), min(A, B)) = mul(A, B)).
cnf(mul_one,axiom,mul(A, num1) = A).
cnf(mul_zero,axiom,mul(A, num0) = num0).
cnf(not_eq_to_ineq,axiom,not(eq(X, Y)) = ne(X, Y)).
cnf(not_gt_to_eqlt,axiom,not(lt(Y, X)) = le(X, Y)).
cnf(not_not,axiom,not(not(X)) = X).
cnf(or_comm,axiom,or(Y, X) = or(X, Y)).
cnf(or_over_and,axiom,or(A, and(B, C)) = and(or(A, B), or(A, C))).
cnf(or_to_and,axiom,or(X, Y) = not(and(not(X), not(Y)))).
cnf(or_x_and_x_y,axiom,or(X, and(X, Y)) = X).
cnf(sub_to_add,axiom,minus(A, B) = plus(A, mul(numneg1, B))).
cnf(if_1,axiom,if(num1, A, B) = A).